---
title: "Course Syllabus"
engine: knitr
format: 
  html: default
  pdf: default
format-links: true
---

Last Updated: `r format(Sys.Date(), "%m/%d/%Y")`

# Course Title {#sec-title}

PSY:2301 – Introduction to Clinical Psychology (Spring 2025)

# Course Meeting Time and Place {#sec-lectureTime}

Monday & Wednesday 10:30–11:20 a.m., 100 Phillips Hall (PH)

# Course Website {#sec-website}

<https://icon.uiowa.edu>

To access the course site, log into [Iowa Courses Online (ICON)](https://icon.uiowa.edu) using your Hawk ID and password.

# Course Home {#sec-home}

The University of Iowa\
The College of Liberal Arts and Sciences\
Department of Psychological and Brain Sciences

The College of Liberal Arts and Sciences (CLAS) is the home of this course, and CLAS governs the add and drop deadlines, academic misconduct policies, and other policies and procedures.
Other UI colleges may have different policies.

# Instructor Contact Information {#sec-instructor}

[Professor Petersen](https://psychology.uiowa.edu/people/isaac-petersen)\
Office: 175 Psychological and Brain Sciences Building (PBSB)\
E-mail: [isaac-t-petersen@uiowa.edu](mailto:isaac-t-petersen@uiowa.edu)\
Office Phone: 467-1014\
Student drop-in hours: Monday 11:20–12:20 & Thursday 2–4\
Note: I'm here to help you learn and succeed in PSY:2301.
Please come to my office hours to ask questions about course material, assignments, exams, or professional development (career-related issues), for instance.
I welcome you to discuss any concerns you might have about the class.
I am also available to meet with you by appointment, although I would appreciate your making every effort to see me during office hours.
The best way to reach me outside of class is by e-mail.

# Discussion Sections {#sec-sections}

All discussion sections are in 53 VAN.
The day and time of the discussion section differ by section:

| Section | Day/Time              | Teaching Assistant |
|:--------|:----------------------|:-------------------|
| A01     | Monday 3:30–4:20      | Olivia Adamson     |
| A02     | Monday 4:30–5:20      | Olivia Adamson     |
| A03     | Tuesday 8:30–9:20     | James Lopez        |
| A04     | Tuesday 12:30–1:20    | Gonzalo Quinones   |
| A05     | Tuesday 1:30–2:20     | James Lopez        |
| A06     | Wednesday 2:30–3:20   | Gonzalo Quinones   |
| A07     | Wednesday 3:30–4:20   | Gonzalo Quinones   |
| A08     | Thursday 9:30–10:20   | Olivia Adamson     |
| A09     | Thursday 10:30–11:20  | Olivia Adamson     |
| A10     | Friday 1:30–2:20      | Gonzalo Quinones   |

# Graduate Teaching Assistants {#sec-TAs}

The class has three graduate teaching assistants (TAs).

Gonzalo Quinones\
Office: 364 Psychological and Brain Sciences Building (PBSB)\
Sections: A04, A06, A07, A10\
Student drop-in hours: Tuesday 10:00–12:00 and Wednesday 9:00–10:00\
E-mail: [gonzalo-quinones@uiowa.edu](mailto:gonzalo-quinones@uiowa.edu)

Olivia Adamson\
Office: 364 Psychological and Brain Sciences Building (PBSB)\
Sections: A01, A02, A08, A09\
Student drop-in hours: Monday 12:00–2:00 (in-person and/or by zoom) and Thursday 8–9am (over zoom)\
E-mail: [olivia-adamson@uiowa.edu](mailto:olivia-adamson@uiowa.edu)

James Lopez\
Office: 364 Psychological and Brain Sciences Building (PBSB)\
Sections: A03, A05\
Student drop-in hours: Monday 9:00–10:30\
E-mail: [james-lopez@uiowa.edu](mailto:james-lopez@uiowa.edu)

# Departmental Resources {#sec-deptResources}

Department of Psychological and Brain Sciences: <https://psychology.uiowa.edu>\
Department of Psychological and Brain Sciences Main Office: G60 Psychological and Brain Sciences Building (335-2406)\
Coordinator of Undergraduate Studies: Professor Windschitl ([paul-windschitl@uiowa.edu](mailto:paul-windschitl@uiowa.edu); 335-3681)\
Academic Coordinator: Janeil Page-Jamison ([janeil-page@uiowa.edu](mailto:janeil-page@uiowa.edu); 384-3657)\
Departmental Executive Officer (DEO)/Department Chair: Professor Blumberg ([mark-blumberg@uiowa.edu](mailto:mark-blumberg@uiowa.edu); 335-2424)

# Prerequisites {#sec-prereqs}

The Psychology department has a hierarchical course structure that requires students to complete certain prerequisites before taking upper-level classes.
The prerequisite for this course is Elementary Psychology (PSY:1001).

# Description of Course {#sec-description}

This course is designed to introduce you to the concepts and methods of the science of clinical psychology.

It has three areas of emphasis:

1. Fundamentals of Scientific Clinical Psychology
1. Evidence-Based Psychological Assessment
1. Evidence-Based Psychological Intervention

This course will provide an introduction to (a) major theoretical models and research methods in scientific clinical psychology; (b) several psychological problems that are particularly relevant to college students (depression, anxiety, and alcohol abuse); (c) the general principles underlying the construction, administration, and interpretation of evidence-based clinical assessments; and (d) empirically supported approaches to psychological intervention.
*You are urged to reconsider your decision to take this class if you are reluctant to examine these topics in a scientific manner.*

Note: Some topics and movies will deal with sensitive or controversial issues such as alcohol problems, depression, anxiety, abuse, sexual assault, eating disorders, and suicide.

# Learning Outcomes {#sec-learningOutcomes}

Taking this course should make you a more informed consumer of claims about contemporary clinical psychology and may assist in your evaluation of clinical psychology or other related potential career goals.
This course is not designed to provide extensive information on the nature of psychological disorders (see Abnormal Psychology course) or to provide you with the skills to assess and treat psychological problems.

# Required Textbook {#sec-textbook}

There isn't a required or recommended textbook.
Instead, this course will include a combination of book chapters, peer-reviewed journal articles, and popular media articles.
The source for all exam questions will be lecture, discussion, and all required readings for lectures and section, which will be provided on the course website on [ICON](https://icon.uiowa.edu).
The cost of textbooks has become so high that I am not comfortable requiring one for this course when I can cover the material adequately in other ways.
There also is no textbook available that covers the material as we do in class.
Attendance at lectures will be critical as a result, however.
If you miss a lecture or section, you will need to watch the lecture recording or get notes from a peer, because we do not provide notes or re-present missed lecture or section material in meetings.
Once you have the notes from a peer, review them carefully on your own, then get into office hours with me or one of the TAs to address any specific questions that you have as soon as possible.
Feel free to come to office hours with me or with one of the TAs to discuss how best to study for a course without a textbook.

# Academic Honesty and Misconduct {#sec-academicHonesty}

All students in CLAS courses are expected to abide by the [college's standards of academic honesty](https://clas.uiowa.edu/students/handbook/academic-fraud-honor-code).
Academic misconduct must be reported by instructors to CLAS according to [these procedures](https://policy.clas.uiowa.edu/clas-policies-and-procedures/undergraduate-education/academic-misconduct-undergraduate).
Please note that collaboration with other classmates on quizzes and during exams is not permitted.
However, I do encourage you to collaborate with classmates to *prepare* for exams (e.g., informal study groups).
In addition, you are expected to follow the course's policy on the use of artificial intelligence (AI), which is outlined below.

# Artificial Intelligence (AI) Policy {#sec-ai}

Because writing, analytical, and critical thinking skills are part of the learning outcomes of this course, all work submitted by students should be prepared by the student.
You are training these cognitive muscles; if you go to the gym, you would not have AI lift the weights for you.
For these reasons, AI-generated submissions are not permitted and will be treated as plagiarism.
Learning these core foundational skills will make you a better user of AI in the future, because you will be better-positioned in the future to critically evaluate AI responses and to identify when (and the ways in which) its responses are inaccurate.
Moreover, in many industries, use of AI is not permitted because you cannot share the company's proprietary information.
Thus, developing strong competencies in these domains (without the use of AI) will prepare you for a competitive workplace.

# Course Requirements and Policies {#sec-requirements}

## Lecture {#sec-lecture}

We will meet twice weekly for lectures, at the time and location described [above](#sec-lectureTime).
My powerpoint presentations for each lecture will be posted on [ICON](https://icon.uiowa.edu) no later than noon the day before a lecture (though I may continue to refine the slides up until the time of lecture).
<u>Please note:</u> powerpoint presentations are an outline of my points. 
<u>It is your responsibility to take notes during class.</u>
I strongly recommend bringing the powerpoint presentations to class to take notes.

You should feel free to ask questions during lecture, although some questions may need to be deferred given the size of the class and the need to complete coverage of specific material during lecture.
<u>Questions and further discussion of class material are always welcome</u> during office hours, during discussion section, and via e-mail.
Please bear in mind that extensive or complex questions may not be addressable over e-mail.

### Lecture Recordings {#sec-recordings}

My intention is to record lectures so that you may review them.
Recorded lectures will be posted on the "UICapture" tab in [ICON](https://icon.uiowa.edu).
Recordings will be available up to 48 hours after class (for Wednesday lectures) or until the Wednesday class period (for Monday lectures).
However, <u>please do not count on recordings being available</u>, in case I accidentally forget to initiate the recording or there is a technical malfunction.
The availability of lecture recordings will not be extended beyond 48 hours after lecture—the recordings are meant to help people keep up with lectures and for students to retrieve the relevant content if they missed anything during the live lecture or if they miss the lecture; they are not meant to be a study method that allows people to fall behind in class from week to week.
If you miss something and are unable to watch the lecture recording, you can get/review notes with a peer, and then come to office hours if you have specific questions.

## Discussion Section {#sec-discussionSection}

In addition to lecture, you also have a weekly discussion section, except during exam weeks.
The day and time of the weekly discussion section differs based on the section, see [above](#sec-sections).

## Attendance and Participation {#sec-attendanceParticipation}

Discussion section attendance and participation are mandatory and will be worth 8% of your final grade.
You must attend section, pay attention, participate verbally, <u>and</u> complete the required activities during section to receive any attendance and participation points, as indicated by your <u>submission of the required written responses during section at the end of the section session</u>.
There will be 13 discussions during the semester, and you will receive one point for submitting an appropriate written response at the end of each section, up to a <u>maximum</u> of 11 points (i.e., you will not receive extra credit for submitting appropriate responses for all 13 discussions).
Thus, you will not be penalized for missing two sections, although you still will be responsible for the covered material on exams, etc., and I urge you strongly to attend all sections.
This strategy is designed to facilitate my management of the excuses associated with an occasional missed section (i.e., no more than two during the semester).
In other words, make sure you attend and participate in at least 11 of your discussion sections this semester!!

If you have to a section for an excusable reason (e.g., you are sick), let your TA know as soon as possible that you will have to miss class—preferably before class, and no later than 48 hours after class.
It is up to our discretion what is considered an excused absence.
If it is an excused absence, a TA will send you notes from the section you missed, and you will be able to submit the in-class writing assignment by emailing it to your TA—<u>you will still need to submit the writing assignment within one week of the missed discussion section to get attendance credit for that section</u>.
If you miss a section, you can attend a different section during the same week <u>only with the permission of the instructor of the different section</u>, <u>but you will not receive attendance and participation points for doing so</u> (unless the absence is excused by the instructor).

Lecture attendance is not mandatory, but it is strongly encouraged; most material presented in lecture is not included in the readings, and lecture recordings may not always be available.
<u>You are responsible for and will be tested on all material presented in lectures, discussion sections, and in the required readings</u>.
Regular attendance and good attention to lectures will improve what you get out of this class and is likely to improve your performance on the exams.

## Readings & Quizzes {#sec-readingQuizzes}

Readings and other materials will be posted on [ICON](https://icon.uiowa.edu).
You are expected to do the readings before discussion section.
You will have an online quiz on the readings to complete in [ICON](https://icon.uiowa.edu), on your own, <u>before</u> each discussion section.
The quizzes are meant to help you come to class prepared to contribute so you are best-positioned to learn and to help others learn.
The quizzes are not timed (you can spend as much time as you need on each quiz up until the deadline).
The deadline for each quiz is 30 minutes before your scheduled discussion section starts.
We will not accept late responses or multiple submissions.
Your lowest quiz score will be dropped.
We will not accept excused absences for quizzes because (a) you have a week to complete the quiz (and can submit it at any point during that week), and (b) we drop your lowest quiz score.
Each quiz will be weighted the same in the final grade.
Quiz answers will be viewable at the end of the week (i.e., after the last discussion section has taken their quiz).

Past experience has shown that in order to do well in this class, you should read the required material, participate actively in class, and go over your notes <u>each week</u>.
There is too much material being covered in this class to try to study only by frantic preparation immediately before exams.
Note that lecture and section will <u>not</u> cover all relevant material for the course; you will be expected to know the <u>required</u> readings for exams.

## Workload {#sec-workload}

This is a 3 semester hour course.
Students should therefore expect to spend [6 additional hours per week](https://clas.uiowa.edu/faculty/student-workload-guidelines) (outside of class) reading the articles, reviewing material from lecture and discussion section, and preparing for quizzes and exams.

## Examinations {#sec-exams}

There will be 3 exams.
Exams 1 and 2 will be administered during class time.
The date, time, and location of the final exam will be announced by the 5th week of class by the College of Liberal Arts and Sciences; the duration of the final exam will be 120 minutes.
The exams will include multiple-choice questions.
Each exam will emphasize information presented for the third of the class that precedes it.
However, some integration of information across sections will be required for questions on the second and third exams.
Exam questions can come from <u>any of the following sources: lectures, sections, or required readings</u>.
For suggested study tips for this class, see [here](howToStudy.qmd).

### Missing Exams {#sec-missingExams}

[University regulations require that students be allowed to make up examinations](https://opsmanual.uiowa.edu/students/absences-class) that have been missed due to illness, religious holy days, military service obligations (including service-related medical appointments), or other unavoidable circumstances or University-sponsored activities.
Students with UI-authorized activities must discuss their absences with the instructor as soon as possible.
Religious obligations must be communicated within the first three weeks of classes.
See below for the documentation necessary for an absence to be excused and to be eligible to take a make-up exam.

Students are allowed to make up exams that have been missed due to illness, mandatory religious observations, official University activities, or other unavoidable circumstances.
Note: the format of the make-up exam may differ from the original exam.
If you know that you must be away at the time of an exam for one of these reasons, Professor Petersen or the TA must be contacted in advance whenever possible to schedule a make-up exam.
In order to take a make-up exam, you must provide acceptable documentation to be eligible to take it: including documentation for any report of illness; any other circumstances must be documented by the University of Iowa [Absence Explanation Form](https://clas.uiowa.edu/sites/clas.uiowa.edu/files/2024-05/ABSENCE%20EXPLANATION%20FORM.pdf) (located in ICON under "Student Tools") and must be approved by Professor Petersen.
<u>In sum, to be eligible for a make-up exam, Professor Petersen or the TA must be contacted before the examination whenever possible, and you must send acceptable form of documentation to Professor Petersen or the TA</u>.

# Grading System and the Use of +/- {#sec-gradingSystem}

Final grades will be assigned at the end of semester on the basis of your total percentage of points earned on exams, quizzes, and section participation, as detailed below.
Grades will be assigned on an absolute scale (criterion-referenced grading); course grades will not be curved.
No extra-credit opportunities are available for this course.
Please note: As a matter of fairness to all students, I assign grades based on performance and do not negotiate grades.
Final grades will be assigned based on the following ranges:

| Grade | Percent |
|:------|:--------|
| A+    | 97–100% | 
| A     | 93–96   |
| A−    | 90–92   |
| B+    | 87–89   |
| B     | 83–86   |
| B−    | 80–82   |
| C+    | 75–79   |
| C     | 70–74   |
| C−    | 65–69   |
| D+    | 60–64   |
| D     | 55–59   |
| D−    | 50–54   |
| F     | < 50%   |

I round up from .5 when determining final grades.
For example, a course percent of 79.50 would receive a B−, whereas a course percent of 79.49 would receive a C+.

# Course Grades {#sec-courseGrades}

Final course grades will be assessed based on your performance in the activities below.
The relative contribution of each component to your final grade is as follows:

 - 28%	Examination #1
 - 28%	Examination #2
 - 28%	Examination #3 (administered only during the class's Final Exam time slot)
 - 8% 	Discussion Attendance/Participation
 - 8% 	Reading Quizzes

# Tentative Course Outline (exam dates fixed) {#sec-outline}

## Section Notes {#sec-sectionNotes}

- Sections will not be held during the week of examinations.
Therefore, sections are cancelled on the following dates: Monday 2/27 – Friday 3/3 and Monday 4/3 – Friday 4/7.

## Unit One {#sec-unit1}

**Unit One: Fundamentals of Scientific Clinical Psychology**

| Date | Topic                                                                     |
|:-----|:--------------------------------------------------------------------------|
| 1/16 | MLK Day (no class!)                                                       |
| 1/18 | Introduction and Contemporary Clinical Psychology                         |
| 1/23 | Classification and Diagnosis                                              |
| 1/25 | Classification and Diagnosis                                              |
| 1/30 | Research Methods in Clinical Psychology (content focus on sexual assault) |
| 2/1  | Research Methods in Clinical Psychology (content focus on sexual assault) |
| 2/6  | Mood Disorders                                                            |
| 2/8  | Mood Disorders                                                            |
| 2/13 | Mood Disorders and Suicide                                                |
| 2/15 | Anxiety Disorders                                                         |
| 2/20 | Anxiety Disorders                                                         |
| 2/22 | Alcohol Use Disorders                                                     |
| 2/27 | Examination #1 (no sections this week!)                                   |

## Unit Two {#sec-unit2}

**Unit Two: Evidence-Based Psychological Assessment and Prediction**

| Date | Topic                                          |
|:-----|:-----------------------------------------------|
| 3/1  | Overview of Assessment and Prediction          |
| 3/6  | Overview of Assessment and Prediction          |
| 3/8  | Interviewing, Observation, and Self-Monitoring |
| 3/13 | Spring Break (no class!)                       |
| 3/15 | Spring Break (no class!)                       |
| 3/20 | Interviewing, Observation, and Self-Monitoring |
| 3/22 | Intelligence Testing                           |
| 3/27 | Intelligence Testing                           |
| 3/29 | Personality Assessment                         |
| 4/3  | Personality Assessment; Wrap Up                |
| 4/5  | Examination #2 (no sections this week!)        |

## Unit Three {#sec-unit3}

**Unit Three: Evidence-Based Psychological Intervention**

| Date | Topic                                                      |
|:-----|:-----------------------------------------------------------|
| 4/10 | Major Approaches to Intervention                           |
| 4/12 | Major Approaches to Intervention                           |
| 4/17 | Cognitive-Behavioral Therapy for Panic Disorder; Transdiagnostic Treatment for Emotional Disorders |
| 4/19 | Evaluation of Interventions                                |
| 4/24 | Evidence-Based Treatments; Influences on Treatment Outcome |
| 4/26 | Dissemination of Evidence-Based Treatments                 |
| 5/1  | Intervention Controversies                                 |
| 5/3  | Wrap-Up                                                    |

# Date and Time of the Final Exam {#sec-finalExam}

The [final examination date and time](https://registrar.uiowa.edu/final-exam-schedules) will be announced by the Registrar generally by the fifth week of classes, and it will be announced on the course ICON site once it is known.
<u>Do not plan your end of the semester travel plans until the final exam schedule is made public.
It is your responsibility to know the date, time, and place of the final exam.</u>
According to the Registrar's final exam policy, students <u>have a maximum of two weeks after the announced final exam schedule</u> to request a change if an exam conflict exists or if a student has more than two exams scheduled for the same day (see the [policy](https://registrar.uiowa.edu/makeup-final-examination-policies) here).

# Course Resources {#sec-courseResources}

There are many course resources available to help you succeed in the class, including:

- Powerpoint slides for lecture
- Powerpoint slides for discussion section
- getting and reviewing missed notes from a peer
- [lecture recordings](#sec-recordings)
- study questions after each lecture (see the "Study Questions" folder under the "Files" tab on [ICON](https://icon.uiowa.edu))
- Quizlet questions (see the "Quizlet" folder under the "Files" tab on ICON)
- practice exam questions that we post leading up to the exam (these will be made available in the "Practice Exam Questions" folder under the "Files" tab on [ICON](https://icon.uiowa.edu))
- review your quizzes and the answers
- our guide on [how to study for the class](howToStudy.qmd)
- TA office hours
- instructor office hours
- [peer study groups](#sec-requests)
- Tutor Iowa: https://tutor.uiowa.edu

# Drop Deadline for this Course {#sec-dropDeadline}

You may drop an individual course before the drop deadline; after this deadline you will need collegiate approval.
You can look up the drop deadline for this course [here](https://registrar.uiowa.edu/course-deadlines).
When you drop a course, a "W" will appear on your transcript.
The mark of "W" is a neutral mark that does not affect your GPA.
To discuss how dropping (or staying in) a course might affect your academic goals, please contact your Academic Advisor.
Directions for adding or dropping a course and other registration changes can be found on the [Registrar's website](https://registrar.uiowa.edu/change-registration-myui).
Students can find policies on dropping CLAS courses [here](https://clas.uiowa.edu/students/students-academic-policies/registration-policies#dropping).

# Feedback about the Course {#sec-feedback}

I welcome feedback at any point during the class.
If you have comments on the class or my teaching, please feel free to meet with me during office hours.

## Student Complaints {#sec-complaints}

Students with a complaint about a grade or a related matter should first discuss the situation with the instructor, and finally with the DEO (Chair) of the department, school, or program offering the course.
Sometimes students will be referred to the department or program's Director of Undergraduate Studies (DUS) or Director of Graduate Studies (DGS).
Students should contact [CLAS Undergraduate Programs](https://clas.uiowa.edu/students/handbook/student-rights-responsibilities#rights) for support when the matter is not resolved at the previous level.

# Communication: UI Email {#sec-email}

Students are responsible for all official correspondences sent to their UI email address (uiowa.edu) and must use this address for any communication with instructors or staff in the UI community.
For the privacy and the protection of student records, UI faculty and staff can only correspond with UI email addresses.

## Other Expectations of Student Performance {#sec-otherExpectations}

Students have the right to a distraction-free learning environment.
You have the responsibility to help create such a classroom environment.
Please treat other students in the class, the TAs, and the instructor with respect.
Students are expected to help each other learn and to contribute overall to the learning environment of the course.
Arriving prepared for class is part of this expectation.

# University Policies {#sec-UIowaPolicies}

[University Policies](https://provost.uiowa.edu/student-course-policies)

[Accommodations for Students with Disabilities](https://provost.uiowa.edu/student-course-policies)\
The University is committed to providing an educational experience that is accessible to all students.
If a student has a diagnosed disability or other disabling condition that may impact the student's ability to complete the course requirements as stated in the syllabus, the student may seek accommodations through [Student Disability Services](https://sds.studentlife.uiowa.edu/students) (SDS).
SDS is responsible for making [Letters of Accommodation (LOA)](https://sds.studentlife.uiowa.edu/students/letter-accommodations-loa) available to the student.
<u>The student must provide a LOA to the instructor as early in the semester as possible, but requests not made at least two weeks prior to the scheduled activity for which an accommodation is sought may not be accommodated.</u>
The LOA will specify what reasonable course accommodations the student is eligible for and those the instructor should provide.
Additional information can be found on the [SDS website](https://sds.studentlife.uiowa.edu/students/apply).

[Class Recordings](https://provost.uiowa.edu/student-course-policies)\
Students may be enrolled in a class where some sessions will be recorded or live-streamed.
Such recordings/streaming will only be available to students registered for the class.
These recordings are the intellectual property of the instructor and they may not be shared or reproduced without the explicit, written consent of the instructor.
Further, students may not share these sessions with those not in the class or upload them to any other online environment.
Doing so would be a breach of the Code of Student Conduct, and, in some cases, a violation of state and federal law, including the Federal Education Rights and Privacy Act (FERPA).

The unauthorized video or audio recording of academic activities (e.g., lectures, course discussions, office hours, etc.) by a student is prohibited.
Students with a reasonable accommodation for recording approved by Student Disability Services should notify each instructor and provide the Letter of Accommodation prior to using the accommodation.
A student may record classroom activities with prior written permission from the instructor and notice to other students in the class that audio or video recording may occur.
Any and all classroom recording must be for personal academic use only.
The distribution, sharing, sale, or posting of recordings on the internet (including social media), in whole or in part, is prohibited and doing so may be a violation of the Code of Student Life and/or state or federal privacy, copyright, or other laws.

- [Free Speech and Expression](https://provost.uiowa.edu/student-course-policies)
- [Non-Discrimination](https://provost.uiowa.edu/student-course-policies)
- [Accommodations for Students with Disabilities](https://provost.uiowa.edu/student-course-policies)
- [Absences from Class](https://provost.uiowa.edu/student-course-policies)
- [Absences for Religious Holy Days](https://provost.uiowa.edu/student-course-policies)
- [Absences for Military Service Obligations](https://provost.uiowa.edu/student-course-policies)
- [Classroom Expectations](https://provost.uiowa.edu/student-course-policies)
- [Sexual Harassment/Misconduct and Supportive Measures](https://provost.uiowa.edu/student-course-policies)
- [Conflict Resolution](https://provost.uiowa.edu/student-course-policies)
- [Mental Health](https://provost.uiowa.edu/student-course-policies)
- [Basic Needs and Student Support](https://provost.uiowa.edu/student-course-policies)
- [Class Recordings](https://provost.uiowa.edu/student-course-policies)

# Course Requests {#sec-requests}

We have a centralized location to keep track of requests, forms, etc., so we can make sure we meet your needs.
Course requests include, for instance, requests to join a peer study group, setting up a time to review your exam, requesting accommodations, etc.
Please submit course requests (e.g., to join a peer study group) here: <mark>[UPDATE LINK!]</mark> <https://uiowa.qualtrics.com/jfe/form/SV_1HUyg6ZaR4CcjWu>.
If you have accessibility accommodations from Student Disability Services (SDS), please submit your SDS accommodations letters at this link.

# Where to Get Academic Support for This Course {#sec-academic-support}

- Drop-in study groups and one-on-one tutoring: student drop-in hours of the graduate TAs and instructor
- Formal tutoring: Tutor Iowa: <https://tutor.uiowa.edu>
- Academic accommodations: <https://sds.studentlife.uiowa.edu>

# Mental Health Resources and Student Support {#sec-mental-health}

Students are encouraged to be mindful of their mental health and seek help as a preventive measure or if feeling overwhelmed and/or struggling to meet course expectations.
Students are encouraged to talk to their instructor for assistance with specific class-related concerns.
For additional support and counseling, students are encouraged to contact University Counseling Service (UCS).
Information about UCS, including resources and how to schedule an appointment, can be found at [counseling.uiowa.edu](http://counseling.uiowa.edu).
Find out more about UI mental health services at: [mentalhealth.uiowa.edu](http://mentalhealth.uiowa.edu), including the 24-7 [UI Support and Crisis Line](https://mentalhealth.uiowa.edu/ui-support-and-crisis-line).

Additionally, the Office of the Dean of Students can help students navigate personal crisis situations.
They can provide one-on-one support, help with identifying options, and access to [basic needs resources (such as food, rent, childcare, etc.)](http://basicneeds.uiowa.edu).
Student Care and Assistance: 132 IMU, [dos-assistance@uiowa.edu](mailto:dos-assistance@uiowa.edu), or 319-335-1162 and more info: [dos.uiowa.edu/assistance](https://dos.uiowa.edu/assistance)

Some of the topics covered in class involve problems that can be quite common among college students.
If you feel that you or someone you know may be struggling with an academic, emotional, or psychological problem, the following organizations are available for assistance:

| Service                                                                    | Contact Info                                                       |
|:---------------------------------------------------------------------------|:-------------------------------------------------------------------|
| University of Iowa Academic Advising Center                                | 353-5700, <https://advisingcenter.uiowa.edu>                       |
| University Counseling Services                                             | 335-7294, <https://www.uiowa.edu/ucs>                              |
| Student Health Service - Mental Health                                     | 335-8394, <https://studenthealth.uiowa.edu/services/psychiatry>    |
| University of Iowa Hospitals and Clinics Adult Psychiatry Services Clinic  | 353-6314, <https://www.uihealthcare.org/Psychiatry>                |
| Seashore Clinic (in the UI Department of Psychological and Brain Sciences) | 335-2467, <https://psychology.uiowa.edu/resources/seashore-clinic> |
| Women's Resource and Action Center                                         | 335-1486, <https://wrac.uiowa.edu>                                 |
| Rape Victim Advocacy Program                                               | 319-335-6000 or 800-228-1625, <https://www.uiowa.edu/~rvap>        |
| Office of Sexual Misconduct                                                | 319-335-6200, <https://osmrc.uiowa.edu>                            |
| CommUnity                                                                  | 855-325-4296, <https://builtbycommunity.org/crisis>                |
| Community & Family Resources                                               | 351-4357, <https://www.cfrhelps.org>                               |

<u>If you or someone you know is contemplating suicide</u>, either call or text the Suicide and Crisis Lifeline at 988, or call 911.

# Disclaimer {#sec-disclaimer}

This syllabus is subject to change.
Any changes will be discussed in class, via email, and/or on [ICON](https://icon.uiowa.edu).
